-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 17:43:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COURSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSES` (
  `NUMBER` INT NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `CREDITS` INT NULL,
  `SYLLABUS` VARCHAR(45) NULL,
  `PRE REQUISITES` VARCHAR(45) NULL,
  PRIMARY KEY (`NUMBER`),
  UNIQUE INDEX `TITLE_UNIQUE` (`TITLE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTUCTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTUCTORS` (
  `ID` INT NOT NULL,
  `DEPARTMENT` VARCHAR(45) NOT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `STUDENT ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `PROGRAM` VARCHAR(45) NULL,
  PRIMARY KEY (`STUDENT ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE OFFERINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE OFFERINGS` (
  `NUMBER` INT NOT NULL,
  `YEAR` YEAR NULL,
  `SEMESTER` INT NULL,
  `SEC NO` VARCHAR(45) NULL,
  `INSTRUCTOR` INT NULL,
  `TIMINGS` VARCHAR(45) NULL,
  `CLASSROOM` VARCHAR(45) NULL,
  PRIMARY KEY (`NUMBER`),
  INDEX `INSTRUCTOR_idx` (`INSTRUCTOR` ASC) VISIBLE,
  CONSTRAINT `NUMBER`
    FOREIGN KEY (`NUMBER`)
    REFERENCES `mydb`.`COURSES` (`NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`INSTRUCTOR`)
    REFERENCES `mydb`.`INSTUCTORS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
